### ISSUE TITLE
ImportError: cannot import name 'STYLE_NUMPY'

### ISSUE THREAD

**Issue by Julienlego** [hsharrison/pyglet2d#6]
I tried running the graphics demo and got an import error. Not exactly sure why but I think it has something to do with polygon3.

**Comment by hsharrison** [comment]
Can you post the full traceback?

**Comment by Julienlego** [comment]
Traceback (most recent call last):
  File "C:/Users/Jules/PycharmProjects/finalproject/src/pyglet2d_demo.py", line 9, in <module>
    from pyglet2d import Shape
  File "C:\Users\Jules\PycharmProjects\finalproject\venv\lib\site-packages\pyglet2d.py", line 7, in <module>
    from Polygon import Polygon, setDataStyle, STYLE_NUMPY
ImportError: cannot import name 'STYLE_NUMPY'

Process finished with exit code 1

**Comment by bdyetton** [comment]
I have this too:
```
Traceback (most recent call last):
  File "C:/Users/Ben.Yetton/NeuroCopter/py_scoreboard/run_scoreboard.py", line 52, in <module>
    import pyglet2d
  File "C:\Users\Ben.Yetton\Anaconda3\lib\site-packages\pyglet2d-0.2.1-py3.6.egg\pyglet2d.py", line 7, in <module>
    from Polygon import Polygon, setDataStyle, STYLE_NUMPY
ImportError: cannot import name 'STYLE_NUMPY'
```

**Comment by hsharrison** [comment]
Sorry I never responded to the previous comment on this issue.

Unfortunately I'm not maintaining this anymore, but I would accept a pull request. This appears to be due to a change in Polygon3 and may not be difficult to fix. Here are options to try:
- try an old version of Polygon3
- find out what the new API is in Polygon3 for `set_data_style(STYLE_NUMPY)`
